# A Machine Learning Approach to Predicting Career Salary Estimates
## Data Cleaning

#### Necessary Libraries

In [1]:
import pandas as pd
import glob
import os

#### Ingesting our collected data by iterating through each file, and then creating a list of data frames

In [9]:
import pandas as pd
import glob


path = os.getcwd()
all_files = glob.glob(path + "/data_collection/data_files/*.csv")

dfs = []

for filename in all_files:
    df = pd.read_csv(filename, index_col=0)
    dfs.append(df)

df = pd.concat(dfs, axis=0, ignore_index=True)

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue
0,IT Manager for Logistics Company,Employer Provided Salary:$80K - $100K,Job Summary:\nSupports all aspects of Company’...,-1.0,"TradePort Logistics, LLC",Georgia,Unknown,-1.0,Company - Public,-1,-1,Unknown / Non-Applicable
1,IT Director,Employer Provided Salary:$80K - $100K,Seeking an experienced IT Director to oversee ...,-1.0,Confidential,"Cranbury, NJ",-1,-1.0,-1,-1,-1,-1
2,Corporate IT Manager,Employer Provided Salary:$85K - $95K,Noregon is looking for a Corporate IT Manager ...,3.6,Noregon Systems\n3.6,"Greensboro, NC",51 to 200 Employees,1993.0,Company - Private,Computer Hardware & Software,Information Technology,$5 to $10 million (USD)
3,IT Manager,Employer Provided Salary:$75K - $85K,Company: A small Entertainment Company located...,-1.0,Confidential,"Los Angeles, CA",-1,-1.0,-1,-1,-1,-1
4,IT Project Manager (Agile delivery experience ...,Employer Provided Salary:$120K - $150K,*** Prefer candidates local to Washington DMV ...,-1.0,Radiant Infotech,"Catonsville, MD",-1,-1.0,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...
48923,Programmer (Mathematician),$73K - $91K (Employer est.),Programmer (Mathematician)\nVideo game\nGaming...,4.3,Thompson Technologies\n4.3,"Johns Creek, GA",201 to 500 Employees,1995.0,Company - Private,Staffing & Outsourcing,Business Services,$25 to $50 million (USD)
48924,Data Scientist - Senior,$73K - $91K (Employer est.),Are you looking for opportunities to use cutti...,3.0,CVS Health\n3.0,Remote,10000+ Employees,1963.0,Company - Public,Health Care Services & Hospitals,Health Care,$10+ billion (USD)
48925,Senior Machine Learning Data Scientist - Telec...,$73K - $91K (Employer est.),Combine two of the fastest-growing fields on t...,3.7,UnitedHealth Group\n3.7,"Eden Prairie, MN",10000+ Employees,1977.0,Company - Public,Health Care Services & Hospitals,Health Care,$10+ billion (USD)
48926,Senior Data Scientist,$73K - $91K (Employer est.),The Office Media Group (OMG) has a simple visi...,4.4,Microsoft\n4.4,"Redmond, WA",10000+ Employees,1975.0,Company - Public,Computer Hardware & Software,Information Technology,$10+ billion (USD)
48927,Data Scientist,$73K - $91K (Employer est.),"Company Summary\nTaking care of our customers,...",4.0,Travelers\n4.0,"Hartford, CT",10000+ Employees,1853.0,Company - Public,Insurance Carriers,Insurance,$10+ billion (USD)